### ISSUE TITLE
Collaboration request

### ISSUE THREAD

**Issue by s-a** [macio97/PBR-Materials#1]
Hello,

I am currently developing a system to share Blender stuff via GitHub as open source. The goal is to provide an easy way for Blender users to share, use and collaborate with blender stuff via GitHub without struggling with technical stuff like `git`. The app will be in `beta` state soon. My idea is to implement the resulting "database" into your Addon. Since my python is very bad it would be nice if you could take this part. Your addon is clean and nice to use. So if you are interested in collaboration send me a [mail](https://github.com/s-a) to discuss further details.

Best regards.

**Comment by macio97** [comment]
Hey, what is the script you are talking about? What specifically does it share on GitHub?

**Comment by s-a** [comment]
Sounds good. Hard to explain all this stuff. 
The Synchronisation of data runs separate in an own app. 

The idea is to attach a resulting database (maybe sql lite) to your blender addon. Where you can search materials and assign them to models in blender. Just like the current functionality of your addon.

I think I can finish a beta this weekend and create some demos about the workflow.

So far this is the workflow to export a material called water and send it to github. It will render preview images and creates a `.blend` file which contains the material.
 
![render1553762736078](https://user-images.githubusercontent.com/1270662/55143321-cbc4b800-513e-11e9-869d-8e93abbfea66.gif)

**Comment by macio97** [comment]
Oh, i get what you are doing, well, i think i'm done with the materials, and if in the future i need to add one more, then it is relatively simple to add and since the PBR addon is using the addon updater then i just have to commit the change. What you are doing is great if you do a lot of materials, this is not the case sorry. If you want you can use my addon code and implement the system you are doing for yourself, maybe share with others ;)

**Comment by s-a** [comment]
Ok, Thank you for your time.
