### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by jplittle75** [macio97/PBR-Materials#4]
I was trying to install your addon today and got this error, and can't figure out how correct it.  

Traceback (most recent call last):

File "C:\Progam Files\Bender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable mode = mod __import__(module_name)

ModuleNotFoundError: No module named 'PBR materials-3'

any help would be welcome 
thanks

**Comment by macio97** [comment]
Ok so, turned out that Blender gives that error because the folder name contains dots, it's an open issue and there is already a patch being worked on by the team [here](https://developer.blender.org/D973), so I will update the Download links soon on my website to not redirect to GitHub but rather download the zip directly, thank you for reporting by the way.

**Comment by jplittle75** [comment]
Thanks so much, I'll keep a look out for that.

**Comment by macio97** [comment]
but since I won't update the website till the 26th of December (because of the release of our first short film) then for now please just grab the 3.4 version (which is the latest one) and rename the folder removing "." and "-"
